### ISSUE TITLE
No work oon NVDA 2024

### ISSUE THREAD

**Issue by alekssamos** [beqabeqa473/CPUMon#2]
I installed the add-on on NVDA 2024.
And I got this error.
```
```
ERROR - globalPluginHandler.listPlugins (13:33:39.733) - MainThread (724):
Error importing global plugin cpuMon
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "...\AppData\Roaming\nvda\addons\cpuMon\globalPlugins\cpuMon\__init__.py", line 12, in <module>
    from . import psutil
  File "...\AppData\Roaming\nvda\addons\cpuMon\globalPlugins\cpuMon\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "...\AppData\Roaming\nvda\addons\cpuMon\globalPlugins\cpuMon\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ModuleNotFoundError: No module named 'globalPlugins.cpuMon.psutil._psutil_windows'

```
```

**Comment by beqabeqa473** [comment]
fixed
